---
##  Playbook to setup windows 

- name: Install packages using win_chocolatey
  win_chocolatey :
    name: "{{package_name}}"
    params: "{{parameters}}"
  when: ansible_distribution =='Microsoft Windows Server 2012 R2 Standard'

- name: Restart  service
  win_service:
    name: "{{service_name }}"
    state: restarted
  when: ansible_distribution =='Microsoft Windows Server 2012 R2 Standard'

- name: Firewall rule to allow traffic
  win_firewall_rule:
    name: "{{service_name}}"
    localport: "{{local_port}}"
    action: allow
    direction: in
    protocol: "{{protocol_name}}"
    state: present
    enabled: yes


