---
##  Playbook to setup 3 tier application
# Alternate Method to create dynmaic inventory
#
- name: Initial Setup to enable the repos in all servers
  hosts: jumpbox 
  gather_facts: false
  become: true
  roles:
    - role: osp-facts
    - role: app_prerequisites



- name: Install and setup load-balancer haproxy in frontend servers
  hosts: frontends
  gather_facts: false
  become: true
  roles:
    - role: load_balancer

- name: Install and setup load-balancer haproxy in frontend servers
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - role: web_server



- name: Install and setup postgres database
  hosts: appdbs
  gather_facts: false
  become: true
  roles:
    - role: db_postgres
...

